/* Covers index1.html's side of the Gemini sprite pipeline: pieceGlyphHtml
 * renders a generated sprite when one exists for that piece, and falls back to
 * the Unicode glyph when one doesn't.
 *
 * The fallback is the important half. Sprites are generated by a manual, paid,
 * network-dependent step (tools/generate-pieces.mjs) and PIECE_SPRITES ships
 * empty, so "no sprites" is the CURRENT shipped state, not a degraded one --
 * these tests are what keep adding the sprite path from having quietly changed
 * how the board renders today. Per-piece fallback also means an interrupted
 * generation run leaves a mixed board rather than holes.
 */
import { test, expect } from "@playwright/test";
import { GAME_URL } from "./helpers.mjs";

// A 1x1 transparent PNG -- enough to be a real, loadable image without
// depending on any generated art being committed.
const FAKE_SPRITE =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk" +
  "YPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==";

test.beforeEach(async ({ page }) => {
  await page.goto(GAME_URL);
});

test("with no sprite generated, pieces render as Unicode glyphs (today's shipped behavior)", async ({ page }) => {
  const [white, black] = await page.evaluate(() => [pieceGlyphHtml("K"), pieceGlyphHtml("k")]);
  expect(white).toContain("<span");
  expect(white).toContain("♔");
  expect(black).toContain("♚");
  expect(white).not.toContain("<img");
});

/* UPDATED 2026-07-28. This used to assert PIECE_SPRITES was EMPTY, which was
 * the shipped truth right up until the pipeline's first successful live call
 * generated b-pawn.png and baked it in. The old assertion failing is the test
 * doing its job -- it is the tripwire for "the sprite path quietly changed how
 * the board renders", and it caught exactly that. What it pins now is the
 * MIXED state, which per-piece fallback makes a supported state rather than a
 * half-finished one: whatever has been generated renders as a sprite, and
 * every piece that has not still renders as its glyph. */
test("every piece in PIECE_SPRITES is a real sprite, and the rest fall back to glyphs", async ({ page }) => {
  const { spriteLetters, allLetters } = await page.evaluate(() => ({
    spriteLetters: Object.keys(PIECE_SPRITES),
    allLetters: Object.keys(SYMBOLS),
  }));
  // No empty/placeholder entries: a key with nothing behind it would render a
  // broken <img> where a perfectly good glyph used to be.
  for (const letter of spriteLetters) {
    const src = await page.evaluate((l) => PIECE_SPRITES[l], letter);
    expect(src, `sprite for ${letter}`).toMatch(/^data:image\/png;base64,.{100,}/);
  }
  for (const letter of allLetters.filter((l) => !spriteLetters.includes(l))) {
    const html = await page.evaluate((l) => pieceGlyphHtml(l), letter);
    expect(html, `ungenerated ${letter} must stay a glyph`).toContain("<span");
    expect(html, `ungenerated ${letter} must not be an <img>`).not.toContain("<img");
  }
});

test("the first generated sprite (b-pawn) is actually wired into the board", async ({ page }) => {
  // The concrete witness that the whole pipeline ran for real: Gemini call ->
  // palette snap -> postprocess -> PNG -> wire-pieces -> rendered <img>.
  const html = await page.evaluate(() => pieceGlyphHtml("p"));
  expect(html).toContain("<img");
  expect(html).toContain("♟");  // glyph retained as alt text
});

test("a piece with a sprite renders as an <img>, carrying its glyph as alt text", async ({ page }) => {
  const html = await page.evaluate((sprite) => {
    PIECE_SPRITES.K = sprite;
    try { return pieceGlyphHtml("K"); } finally { delete PIECE_SPRITES.K; }
  }, FAKE_SPRITE);

  expect(html).toContain("<img");
  expect(html).toContain('class="piece sprite"');
  expect(html).toContain('data-side="w"');
  expect(html).toContain(FAKE_SPRITE);
  // The sprite is the piece's only on-board identity, so a screen reader or a
  // failed image load must still be able to say which piece this is.
  expect(html).toContain('alt="♔"');
});

test("pieces without a sprite still fall back to glyphs while others use sprites", async ({ page }) => {
  const { king, queen } = await page.evaluate((sprite) => {
    PIECE_SPRITES.K = sprite;
    try {
      return { king: pieceGlyphHtml("K"), queen: pieceGlyphHtml("Q") };
    } finally { delete PIECE_SPRITES.K; }
  }, FAKE_SPRITE);

  expect(king).toContain("<img");
  expect(queen).toContain("<span");
  expect(queen).toContain("♕");
});

test("terrain and empty squares stay empty on the sprite path too", async ({ page }) => {
  const results = await page.evaluate((sprite) => {
    PIECE_SPRITES.K = sprite;
    try { return ["", "#", "X"].map((cell) => pieceGlyphHtml(cell)); } finally { delete PIECE_SPRITES.K; }
  }, FAKE_SPRITE);
  for (const html of results) expect(html).toBe("");
});

test("sprites render pixelated and White sprites get a read-on-light-squares outline", async ({ page }) => {
  const style = await page.evaluate(() => {
    const img = document.createElement("img");
    img.className = "piece sprite";
    img.dataset.side = "w";
    document.body.appendChild(img);
    const computed = getComputedStyle(img);
    const result = { rendering: computed.imageRendering, filter: computed.filter };
    img.remove();
    return result;
  });
  // Without this the browser smooths 32px art back up to board size and blurs
  // away exactly the hard pixel edges the art is made of.
  expect(style.rendering).toBe("pixelated");
  // text-shadow (the glyph halo) does nothing to an <img>, so White sprites
  // need the equivalent as a filter or they vanish on light squares -- the
  // exact bug piece-visibility.spec.mjs exists for, on the new render path.
  expect(style.filter).not.toBe("none");
});
