// Fuzzes spawnBlackArmy the way the project's earlier (untracked) regression
// suite did: 30 floors x 28 simulated days = 840 combinations, asserting the
// one safety invariant spawnBlackArmy promises -- a freshly spawned floor
// never leaves White dead on arrival (see whiteSurvivesNextMove).
//
// The narrative campaign's early/mid floors are scripted (fixed, no RNG --
// see NARRATIVE_STAGES), not generated by the procedural budget/tier logic
// these tests exist to fuzz. Every test here that sweeps a floor range
// offsets past NARRATIVE_STAGES.length so it's still exercising the actual
// procedural system, not silently re-checking hand-authored content that
// happens to satisfy the same assertions for unrelated reasons.
import { test, expect } from "@playwright/test";
import { GAME_URL } from "./helpers.mjs";

const SWEEP_SIZE = 30;
const FAKE_DAYS = Array.from({ length: 28 }, (_, i) => i + 1);

async function proceduralFloors(page, count) {
  const stageCount = await page.evaluate(() => NARRATIVE_STAGES.length);
  return Array.from({ length: count }, (_, i) => stageCount + i + 1);
}

test("spawned army never leaves White dead on arrival (840 floor x day combinations)", async ({ page }) => {
  await page.goto(GAME_URL);
  const floors = await proceduralFloors(page, SWEEP_SIZE);

  const failures = await page.evaluate(([floors, days]) => {
    const bad = [];
    for (const floor of floors) {
      for (const day of days) {
        // todayKey() is the only source of day-to-day entropy in the spawn
        // seed; overriding it lets one page fuzz many "days" without needing
        // to fake the system clock.
        todayKey = () => "dTEST" + day;
        state.board = Array.from({ length: 9 }, () => Array(8).fill(""));
        state.board[8][4] = "K";
        state.floor = floor;
        state.lastSpawnBudget = 0;
        spawnBlackArmy();
        if (!whiteSurvivesNextMove(state.board)) bad.push({ floor, day });
      }
    }
    return bad;
  }, [floors, FAKE_DAYS]);

  expect(failures).toEqual([]);
});

test("spawn budget only ratchets up across increasing floors, never down", async ({ page }) => {
  await page.goto(GAME_URL);

  const budgets = await page.evaluate(() => {
    todayKey = () => "dTESTratchet";
    state.board = Array.from({ length: 9 }, () => Array(8).fill(""));
    state.board[8][4] = "K";
    state.lastSpawnBudget = 0;
    const seen = [];
    for (let floor = 1; floor <= 40; floor++) {
      state.floor = floor;
      spawnBlackArmy();
      seen.push(state.lastSpawnBudget);
    }
    return seen;
  });

  for (let i = 1; i < budgets.length; i++) {
    expect(budgets[i]).toBeGreaterThanOrEqual(budgets[i - 1]);
  }
});

test("spawning is deterministic: same floor and day always produces the same board", async ({ page }) => {
  await page.goto(GAME_URL);

  const [first, second] = await page.evaluate(() => {
    function spawnOnce() {
      todayKey = () => "dTESTdeterminism";
      state.board = Array.from({ length: 9 }, () => Array(8).fill(""));
      state.board[8][4] = "K";
      state.floor = 12;
      state.lastSpawnBudget = 0;
      spawnBlackArmy();
      return state.board.map(row => row.join(",")).join("|");
    }
    return [spawnOnce(), spawnOnce()];
  });

  expect(first).toBe(second);
});

// Regression for a reported gameplay bug ("pawn on b44 can't advance,
// highlighted yellow no green dot", floor 6): a scripted NARRATIVE_STAGES row
// that doesn't sum to exactly BOARD_COLS silently corrupts the board. Rows are
// laid down with parseFenRow, which only treats digits 1-8 as empty runs, so
// an over-wide row (e.g. "2b3b2" = 9 cells) makes state.board[y] longer than 8
// and boardToFen later re-emits a "9" run that parseFenRow reads back as a
// bogus one-cell "9" piece -- squares ahead of a pawn read as neither empty
// nor enemy, so it has no legal move. An under-wide row leaves a trailing
// column undefined, with the same effect. Pin every stage row to 8 columns so
// this whole class can't recur; floors 6 and 10 had three such rows.
test("every scripted narrative stage row is exactly BOARD_COLS wide", async ({ page }) => {
  await page.goto(GAME_URL);

  const badRows = await page.evaluate(() => {
    const bad = [];
    NARRATIVE_STAGES.forEach((stage, si) => {
      stage.rows.forEach((row, ri) => {
        const width = parseFenRow(row).length;
        if (width !== BOARD_COLS) bad.push({ stage: stage.label, si, ri, row, width });
      });
    });
    return bad;
  });

  expect(badRows).toEqual([]);
});

// Directly exercises the above through the real spawn path: placing any
// scripted stage on a fresh board must leave every row exactly BOARD_COLS
// wide, since a wider/narrower row is what strands a pawn behind it.
test("placing each scripted stage leaves every board row BOARD_COLS wide", async ({ page }) => {
  await page.goto(GAME_URL);

  const badFloors = await page.evaluate(() => {
    const bad = [];
    for (let floor = 1; floor <= NARRATIVE_STAGES.length; floor++) {
      state.board = Array.from({ length: 9 }, () => Array(8).fill(""));
      state.board[8][4] = "K";
      state.floor = floor;
      state.spawned = false;
      state.lastSpawnBudget = 0;
      spawnBlackArmy();
      const widths = state.board.map(row => row.length);
      if (widths.some(w => w !== BOARD_COLS)) bad.push({ floor, widths });
    }
    return bad;
  });

  expect(badFloors).toEqual([]);
});

// Pins the pawn-supply tuning (PAWN_ALLOWANCE_CHANCE): pawns feed the
// promotion and captured-pawn-carryover mechanics, and without a deliberate
// allowance the tiered budget spends almost entirely on stronger pieces at
// higher floors (measured ~0.7 pawns/floor, >50% of floors with none at
// all). Same 30x28 sweep as the safety-invariant test above, checking the
// resulting average lands near the "about one pawn a floor" target instead
// of drifting back down if the spawn formula changes again later.
test("pawn supply averages roughly one per floor across floors and days", async ({ page }) => {
  await page.goto(GAME_URL);
  const floors = await proceduralFloors(page, SWEEP_SIZE);

  const avgPawnsPerFloor = await page.evaluate(([floors, days]) => {
    let totalPawns = 0, samples = 0;
    for (const floor of floors) {
      for (const day of days) {
        todayKey = () => "dTESTpawns" + day;
        state.board = Array.from({ length: 9 }, () => Array(8).fill(""));
        state.board[8][4] = "K";
        state.floor = floor;
        state.lastSpawnBudget = 0;
        spawnBlackArmy();
        for (const row of state.board) for (const c of row) if (c === "p") totalPawns++;
        samples++;
      }
    }
    return totalPawns / samples;
  }, [floors, FAKE_DAYS]);

  // "Approximately one" per the original ask, not pinned to exactly 1 --
  // wide enough to allow re-tuning PAWN_ALLOWANCE_CHANCE without a false
  // failure, tight enough to catch the allowance being lost entirely.
  expect(avgPawnsPerFloor).toBeGreaterThan(0.8);
  expect(avgPawnsPerFloor).toBeLessThan(1.4);
});

// Regression for a reported exploit: a player's own carried-over material
// used to inflate the same budget the piece-tier loop spends from, so a
// snowballed carryover could buy Black an extra strong piece -- skewable by
// reshuffling what White carries between floors. The carryover bonus should
// only ever buy extra pawns, never change piece-tier composition.
test("carryover bonus buys extra pawns only, never inflates piece-tier composition", async ({ page }) => {
  await page.goto(GAME_URL);

  const { nonPawnPieces, pawnCount } = await page.evaluate(() => {
    todayKey = () => "dTESTbonus";
    // Needs a floor whose own base budget is too small to afford anything
    // but pawns (so any non-pawn piece appearing must have come from the
    // bonus) -- floor 1 is exactly that, but it's also a scripted
    // NARRATIVE_STAGES entry now. Empty the campaign for this call only so
    // floor 1 goes through the real procedural budget/tier logic this test
    // exists to check, then restore it.
    const savedStages = NARRATIVE_STAGES.splice(0);
    try {
      // Three carried-over Amazons is far more material than floor 1's own
      // budget -- if the bonus ever leaked into the tier loop, this would
      // spawn a strong piece despite being floor 1.
      state.board = Array.from({ length: 9 }, () => Array(8).fill(""));
      state.board[8][4] = "K";
      state.board[8][0] = "M";
      state.board[8][1] = "M";
      state.board[8][2] = "M";
      state.floor = 1;
      state.lastSpawnBudget = 0;
      spawnBlackArmy();
    } finally {
      NARRATIVE_STAGES.push(...savedStages);
    }

    let nonPawnPieces = 0, pawnCount = 0;
    for (const row of state.board) {
      for (const c of row) {
        if (!c || c === "K" || c === "M") continue; // empty, or White's own carried-over pieces
        if (c === "p") pawnCount++; else nonPawnPieces++;
      }
    }
    return { nonPawnPieces, pawnCount };
  });

  expect(nonPawnPieces).toBe(0);
  expect(pawnCount).toBeGreaterThan(0);
});
